[pytest]
addopts = -v --alluredir=report/allure-results --clean-alluredir
testpaths = src/tests/test_pod_functions.py
markers =
    smoke: quick smoke tests
    regression: full suite tests
    critical: critical path validation