[pytest]
addopts = -v --capture=tee-sys --html=src/reports/report.html --self-contained-html
testpaths = src/tests
markers =
    smoke: quick smoke tests
    regression: full suite tests
    critical: critical path validation